**Index ile Elemanlara Erişmek**

In [1]:
import numpy as np 
a = np.random.randint(10, size= 10 )
a

array([9, 3, 3, 5, 1, 6, 3, 1, 0, 3])

In [2]:
a[0]

9

In [3]:
a[-2]

0

In [4]:
a[0]=100

In [5]:
a

array([100,   3,   3,   5,   1,   6,   3,   1,   0,   3])

In [7]:
m = np.random.randint(10, size= (3,5) )
m

array([[0, 3, 0, 3, 8],
       [1, 4, 6, 9, 3],
       [4, 3, 6, 0, 7]])

In [8]:
m[0,0]

0

In [9]:
m[1,1]

4

In [10]:
m[1,4]

3

In [11]:
m[1,4]=98

In [12]:
m

array([[ 0,  3,  0,  3,  8],
       [ 1,  4,  6,  9, 98],
       [ 4,  3,  6,  0,  7]])

**Array Alt Kümesine Erişmek(Slicing ile Elemanlara Erişmek)**

In [13]:
import numpy as np

In [14]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
a[1::2]

array([21, 23, 25, 27, 29])

In [16]:
a[:3]

array([20, 21, 22])

In [17]:
a[2::2]

array([22, 24, 26, 28])

In [18]:
#iki boyutlu slice işlemleri

In [19]:
m = np.random.randint(10, size= (5,5))

In [20]:
m

array([[6, 9, 1, 0, 4],
       [6, 7, 0, 4, 3],
       [1, 4, 6, 9, 3],
       [7, 8, 7, 9, 4],
       [8, 1, 6, 2, 0]])

In [21]:
m[:,1]

array([9, 7, 4, 8, 1])

In [22]:
m[:,3]

array([0, 4, 9, 9, 2])

In [23]:
m[4,:]

array([8, 1, 6, 2, 0])

In [24]:
m[2,:]


array([1, 4, 6, 9, 3])

In [25]:
m[2,3]

9

In [26]:
 m[0:2,0:3]

array([[6, 9, 1],
       [6, 7, 0]])

In [27]:
m[::,:2]

array([[6, 9],
       [6, 7],
       [1, 4],
       [7, 8],
       [8, 1]])

In [28]:
m[1:3, 0:2]

array([[6, 7],
       [1, 4]])

**Alt Küme Üzerinde İşlem Yapmak**

In [29]:
import numpy as np 
a =np.random.randint(10, size=(5,5))
a

array([[0, 0, 7, 5, 4],
       [3, 5, 3, 1, 6],
       [2, 2, 4, 6, 7],
       [7, 4, 2, 2, 0],
       [7, 3, 7, 8, 9]])

In [32]:
alt_a=a[0:3,0:2]
alt_a

array([[0, 0],
       [3, 5],
       [2, 2]])

In [33]:
alt_a[0,0] =9999
alt_a[1,1]=888

In [34]:
alt_a

array([[9999,    0],
       [   3,  888],
       [   2,    2]])

In [35]:
a

array([[9999,    0,    7,    5,    4],
       [   3,  888,    3,    1,    6],
       [   2,    2,    4,    6,    7],
       [   7,    4,    2,    2,    0],
       [   7,    3,    7,    8,    9]])

In [36]:
#burada seçilen parçada değişen sayı ana array'de değişti
#değişmemesi için copy() methodu ile alt kümeyi ana array,2den ayırarak array'den abğımsızlaştırarak işlem yapılmasını sağlar.

In [37]:
m=np.random.randint(10, size=(5,5))
m

array([[3, 6, 0, 6, 4],
       [1, 4, 3, 3, 7],
       [7, 8, 7, 5, 2],
       [8, 9, 4, 9, 0],
       [2, 6, 3, 2, 8]])

In [38]:
alt_b = m[0:3,0:2].copy()
alt_b

array([[3, 6],
       [1, 4],
       [7, 8]])

In [39]:
m

array([[3, 6, 0, 6, 4],
       [1, 4, 3, 3, 7],
       [7, 8, 7, 5, 2],
       [8, 9, 4, 9, 0],
       [2, 6, 3, 2, 8]])

**Fancy Index iel Elemanlara Erişmek**

In [1]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
v[3]


9

In [3]:
v[1]

3

In [22]:
v[5]

15

In [ ]:
#bir arada gözlemlemek için;

In [5]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [21]:
#çok fazla index sorgulama işlemini nasıl yapıyoruz? Fancy index ile

In [7]:
al_getir = [1,3,5]

In [8]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [9]:
v[al_getir]

array([ 3,  9, 15])

In [10]:
#iki boyutta fancy

In [11]:
m=np.arange(9).reshape((3,3))

In [12]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [14]:
m[satir,sutun]

array([1, 5])

In [15]:
#basit index ile fancy index

In [16]:
m


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
m[0,[1,2]]

array([1, 2])

In [20]:
#slice ile fancy

In [19]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])