**Yeniden Şekillendirme (reshaping)**

In [1]:
import numpy as np

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a=np.arange(1,10)

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.ndim

1

In [8]:
b=a.reshape((1,9))

In [9]:
 b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
b.ndim

2

**Array Birleştirme(Concatenation)**


In [11]:
import numpy as np

In [12]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [17]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [18]:
z=np.array([7,8,9])

In [19]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#İki boyut

In [21]:
a = np.array([[1,2,3],
              [4,5,6]])

In [22]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Array Ayırma(Splitting)**

In [24]:
import numpy as np

In [25]:
x=np.array([1,2,3,99,99,3,2,1])

In [26]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [33]:
a,b,c = np.split(x, [3,5])

array([3, 2, 1])

In [28]:
a

array([1, 2, 3])

In [29]:
b

array([99, 99])

In [30]:
c

array([3, 2, 1])

In [31]:
#İki boyutlu ayırma

In [32]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [45]:
ust,alt=np.vsplit(m, [2])

In [46]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [48]:
sag, sol=np.hsplit(m, [2])

In [49]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [50]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Array Sıralama(Sorting)**

In [51]:
import numpy as np

In [52]:
v =np.array([2,5,8,9,6,7,4,1,3])

In [53]:
v

array([2, 5, 8, 9, 6, 7, 4, 1, 3])

In [54]:
np.sort(v)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
v

array([2, 5, 8, 9, 6, 7, 4, 1, 3])

In [56]:
v.sort()

In [57]:
v

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#iki boyutlu 

In [59]:
m = np.random.normal(20,5,(3,5))
m

array([[19.92278716, 11.17653152, 20.52384382, 23.54613642, 16.82933806],
       [13.76003587, 20.11924505, 24.81898704, 17.72248607, 20.56468007],
       [16.50462519, 16.93115434, 20.28833434, 14.69959234, 23.95448065]])

In [60]:
np.sort(m, axis=1)

array([[11.17653152, 16.82933806, 19.92278716, 20.52384382, 23.54613642],
       [13.76003587, 17.72248607, 20.11924505, 20.56468007, 24.81898704],
       [14.69959234, 16.50462519, 16.93115434, 20.28833434, 23.95448065]])

In [61]:
np.sort(m, axis=0)

array([[13.76003587, 11.17653152, 20.28833434, 14.69959234, 16.82933806],
       [16.50462519, 16.93115434, 20.52384382, 17.72248607, 20.56468007],
       [19.92278716, 20.11924505, 24.81898704, 23.54613642, 23.95448065]])