**Koşullu Eleman İşlemleri**

In [1]:
import numpy as np

In [3]:
v=np.array([1,2,3,4,5])

In [4]:
v < 3

array([ True,  True, False, False, False])

In [5]:
#kontrol ile koşulun sağlayanlar veya sağlanmayanları nasıl yakalarız?

In [6]:
v[v < 3]

array([1, 2])

In [7]:
v[v > 3]

array([4, 5])

In [8]:
v[v <= 3]

array([1, 2, 3])

In [9]:
v[v >= 3]

array([3, 4, 5])

In [10]:
v[v == 3]

array([3])

In [11]:
v[v != 3]

array([1, 2, 4, 5])

In [12]:
v

array([1, 2, 3, 4, 5])

In [13]:
v*2

array([ 2,  4,  6,  8, 10])

In [14]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [15]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [16]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

**Matematiksel İşlemler**

In [17]:
import numpy as np
v=np.array([1,2,3,4,5])

In [18]:
v-1

array([0, 1, 2, 3, 4])

In [19]:
v*5

array([ 5, 10, 15, 20, 25])

In [20]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

**ufunc** 
* add:ekleme
* substract:çıkarma
* multiply:çarpma
* divide:
* power:kuvvet alma
* mod:kalan
* absolute: mutlak değer
* **cheat sheet** google da aradığımız şeyin sonuna eklersek daha derli toplu sonuçlar alırız.

In [22]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [23]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [27]:
np.subtract(v,1) 

array([0, 1, 2, 3, 4])

In [28]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [29]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [30]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [32]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [33]:
np.absolute(np.array([-3]))

array([3])

In [34]:
np.sin(360)

0.9589157234143065

In [35]:
np.cos(180)

-0.5984600690578581

In [36]:
v=np.array([1,2,3])

In [37]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [38]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [39]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [40]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\fatma\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\fatma\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >