**Numpy Array'i Oluşturmak**


In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [5]:
  np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [ ]:
#Sifirdan Array Olusturma

In [7]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [11]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.random.normal(10,4,(3,4))

array([[19.00022503, 13.39605939,  9.78737353, 11.38738558],
       [12.02603251, 12.62982464, 12.81645196,  5.21383002],
       [ 3.44860704,  6.31880102,  6.49055184,  5.83434482]])

In [14]:
np.random.randint(0,10,(3,3))

array([[0, 4, 4],
       [2, 4, 5],
       [3, 9, 5]])

**Numpy Array Özellikleri**


* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [17]:
import numpy as np

In [20]:
np.random.randint(10, size=10)

array([0, 3, 8, 4, 5, 6, 4, 5, 9, 4])

In [21]:
a=np.random.randint(10, size=10)

In [22]:
a.ndim

1

In [23]:
a.shape

(10,)

In [24]:
a.size

10

In [25]:
a.dtype

dtype('int32')

In [26]:
b=np.random.randint(10, size=(3,5))

In [27]:
b

array([[3, 4, 2, 3, 8],
       [0, 0, 3, 7, 4],
       [8, 9, 0, 7, 8]])

In [28]:
b.ndim

2

In [29]:
b.shape

(3, 5)

In [30]:
b.size

15

In [31]:
b.dtype

dtype('int32')